name: 'npm audit action'
description: 'run npm audit'
author: 'Naoki Oketani <okepy.naoki@gmail.com>'
inputs:
  audit_level:
    description: 'The value of `--audit-level` flag'
    default: low
    required: false
  production_flag:
    description: 'Run npm audit with --production'
    default: 'false'
    required: false
  github_context:
    description: 'The `github` context'
    default: ${{ toJson(github) }}
    required: false
  github_token:
    description: 'GitHub access token used to create an issue'
    required: true
  issue_assignees:
    description: 'Issue assignees (separated by comma)'
    required: false
  issue_labels:
    description: 'Issue labels (separated by comma)'
    required: false
  add_pr_labels:
    description: 'add labels to the PR indicating the issue severity based on audit results'
    default: 'false'
    required: false
  fail_on_vulnerabilities_found:
    description: 'If the action should fail when vulnerabilities are found'
    default: 'false'
    required: false
  issue_title:
    description: 'Issue title'
    default: 'npm audit found vulnerabilities'
    required: false
  working_directory:
    description: 'The directory which contains package.json (since v1.4.0)'
    required: false
  dedupe_issues:
    description: 'Flag to de-dupe against open issues'
    default: 'false'
    required: false
outputs:
  npm_audit:
    description: 'The output of the npm audit report in a text format'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'orange'
