name: daily scan

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: jeffsays/npm-audit-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: jeffsays
          issue_labels: dependencies,vulnerability
          dedupe_issues: true
